# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/ronak.patel124421@gmail.com/dimensional-tables")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM e-commerce-project.dlt_schema.sample_trips_dimensional_tables"))

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table if exists `e-commerce-project`.dlt_schema.products_stg

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from `e-commerce-project`.source_dimensional_tables.customers